name: 機能提案
description: 改善提案や新機能の要望
title: "feat: <短い説明>"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: 改善の背景と具体的な価値が伝わるようにご記載ください。

  - type: textarea
    id: summary
    attributes:
      label: 要望の要約
      placeholder: どのユーザーにとって、何が良くなるか？
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 背景・モチベーション
      placeholder: 現状の課題、どのような問題を解決したいか
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 提案内容（仕様の概略）
      placeholder: 入出力、UI/CLI、影響範囲、後方互換性 など
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案（あれば）
      placeholder: 検討した他の方法と、それを採用しない理由

  - type: checkboxes
    id: checklist
    attributes:
      label: チェックリスト
      options:
        - label: 破壊的変更（Breaking Change）は発生しません
        - label: 実験スクリプトの使い勝手を損ねません

